# Generated by Django 5.1 on 2024-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_updated_at_post_changed_at_comment_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='changed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='changed_at',
            field=models.DateTimeField(),
        ),
    ]
