# Generated by Django 5.1 on 2024-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_changed_at_alter_post_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
