# Generated by Django 5.1 on 2024-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comment_changed_by_alter_post_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='changed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='changed_at',
            field=models.DateTimeField(),
        ),
    ]
