# Generated by Django 5.1 on 2024-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_changed_at_alter_post_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
